# Site settings
title: CoolerPal
email: hi@getcoolerpal.com
description: Smartify your existing Devices
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getcoolerpal.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [README.md, Website.iml, gulpfile.js, bower.json, package.json, node_modules]
