# Site settings
title: SwitchPal
email: hi@getswitchpal.com
description: Smartify your existing Devices
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getswitchpal.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [README.md, Website.iml, gulpfile.js, bower.json, package.json, node_modules]
